export enum ChatEvents {
  JOIN = 'join',
  LEAVE = 'leave',
  USER_JOINED = 'userJoined',
  SEND_MESSAGE = 'sendMessage',
  NEW_MESSAGE = 'newMessage',
  TYPING = 'typing',
  USER_TYPING = 'userTyping',
  DELETE_MESSAGE = 'deleteMessage',
  EDIT_MESSAGE = 'editMessage',
  MESSAGE_EDITED = 'messageEdited',
  ERROR = 'ERROR',
  PRESENCE = 'presence',
  MARK_READ = 'markRead',
  ROOM_ACTIVITY = 'roomActivity',
  ROOM_ADDED = 'roomAdded',
  ROOM_REMOVED = 'roomRemoved',
  PRESENCE_SNAPSHOT = 'presenceSnapshot',
}
