export enum ChatEvents {
  JOIN = 'join',
  LEAVE = 'leave',
  USER_JOINED = 'userJoined',
  SEND_MESSAGE = 'sendMessage',
  NEW_MESSAGE = 'newMessage',
  TYPING = 'typing',
  USER_TYPING = 'userTyping',
  DELETE_MESSAGE = 'deleteMessage',
  ERROR = 'ERROR',
  PRESENCE = 'presence',
  MARK_READ = 'markRead',
  ROOM_ACTIVITY = 'roomActivity',
  PRESENCE_SNAPSHOT = 'presenceSnapshot',
}
