name: "CI - Lint, Build & Test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: "Run Unit Tests"
    runs-on: ubuntu-latest

    env:
      TEST_ENV: "ci"
      JWT_SECRET: "${{ secrets.JWT_SECRET }}"
      VITE_API_URL: "${{ secrets.VITE_API_URL }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Backend dependencies
        run: cd backend && npm install

      - name: Generate Prisma client
        run: cd backend && npx prisma generate

      - name: Lint Backend
        run: cd backend && npx eslint "{src,test}/**/*.ts"

      - name: Build Backend
        run: cd backend && npm run build

      - name: Run Backend tests
        run: cd backend && npm test

      - name: Run Backend e2e tests
        run: cd backend && npm run test:e2e

      - name: Install Frontend dependencies
        run: cd frontend && npm install

      - name: Lint Frontend
        run: cd frontend && npm run lint

      - name: Build Frontend
        run: cd frontend && npm run build

      - name: Run Frontend tests
        run: cd frontend && npm test
